version: '3'
services:
  mongodb:
    image: pvgomes/datomic:latest
    container_name: datomic
    ports:
      - "4334"
      - "4336"
    networks:
      - production-network
    environment:
      - DATOMIC_PASSWORD=datomic
      - ADMIN_PASSWORD=admin
networks:
  production-network:
    driver: bridge