version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - production-network
  dump:
    build: ./docker/dump
    depends_on:
      - "mongodb"
    networks:
      - production-network
#  app:
#    build:
#      dockerfile: ./docker/app/Dockerfile
#      context: .
#    container_name: app
#    volumes:
#     - .:/usr/src/app
#    ports:
#      - "42487"
#    networks:
#      - production-network
#    depends_on:
#      - "mongodb"
networks:
  production-network:
    driver: bridge